``` uml
@startuml OAuth2.0

hide footbox

participant ユーザー
participant App
participant 認可サーバー
participant リソースサーバー

ユーザー -> App: 認証開始

group 認可リクエスト
  ユーザー <-- App: 認可サーバーへのリダイレクト
  ユーザー -> 認可サーバー: 認可サーバーへのリダイレクト
  note right: 認可エンドポイントへ

  App <-- 認可サーバー: 認可画面を返す
  ユーザー <-- App : 認可画面を表示する
  ユーザー -> 認可サーバー: 認可リクエストを承認する
  App <-- 認可サーバー: 認可コードを発行
end

group アクセストークン要求
  App -> 認可サーバー: 認可コードを提示
  note right: トークンエンドポイントへ

  App <-- 認可サーバー: アクセストークンを発行する
end 

group リソースへのアクセス
  App -> リソースサーバー: アクセストークンを提示してリソースを要求
  App <-- リソースサーバー: レスポンス
end 

@enduml
```